keys:
  - &panza age15c0a468t76uw2su43y4c7cmryjn3lt36r0p2fc5vmpmzm322aymq4ntcm6
  - &potato age1ll6jwsnqd39e7shyw77xz27dmmsl96ds94dvvcdgk3ngy0xhhajsypk6kr
creation_rules:
  - path_regex: hosts/panza/secrets/secrets.yaml$
    key_groups:
      - age:
        - *panza
  - path_regex: hosts/potato/secrets/secrets.yaml$
    key_groups:
      - age:
        - *potato
