keys:
  - &kerry age15c0a468t76uw2su43y4c7cmryjn3lt36r0p2fc5vmpmzm322aymq4ntcm6
  # - &potato <insert key here>
creation_rules:
  - path_regex: hosts/panza/secrets.yaml$
    key_groups:
      - age:
        - *kerry
  - path_regex: users/kerry/secrets.yaml$
    key_groups:
      - age:
        - *kerry
